### ISSUE TITLE
others cant hear the song playing

### ISSUE THREAD

**Issue by BlaNKtext** [zhycorp/music-bot-example#21]

**Comment by mzrtamp** [comment]
Hmm, what kind?

**Comment by hansputera** [comment]
Can u show the logs ?

**Comment by mozartrafi** [comment]
Maybe I should reopen this topic, because of the many possible errors caused by the client or maybe with us

**Comment by mozartrafi** [comment]
This kind of error also feels passive, so it might appear at times or depending on the use of the client

**Comment by inhydrox** [comment]
I don't think that's the issue with code

**Comment by mozartrafi** [comment]
Yeaa :/

**Comment by inhydrox** [comment]
Then close this issue lol
