### ISSUE TITLE
Add spotify

### ISSUE THREAD

**Issue by PavelHouze** [zhycorp/music-bot-example#49]
Hello, I wanted to add a spotify API to search track names from spotify url and then play it with ytdl. But it doesnt work at all. Can you add smth like this?

**Comment by KurokuTetsuya** [comment]
`ytdl` = Youtube downloader. You can't use youtube downloader to download spotify.

**Comment by KurokuTetsuya** [comment]
Also this is just an example project, do it yourself don't depend on others

**Comment by PavelHouze** [comment]
Sorry, I mean that i get song name from Spotify api and then try to search it in YouTube.searchsong. I tried a lot of ways to search it in YouTube.searchsong and it doesn't work. 
My last hope was that you can help me or you have an example with Spotify integration.
Anyway, thank you for such a good bot.

**Comment by mozartrafi** [comment]
🤦

**Comment by KurokuTetsuya** [comment]
> Sorry, I mean that i get song name from Spotify api and then try to search it in YouTube.searchsong. I tried a lot of ways to search it in YouTube.searchsong and it doesn't work.
> My last hope was that you can help me or you have an example with Spotify integration.
> Anyway, thank you for such a good bot.

Simple, not all songs on spotify available on youtube. You can use [this](https://www.npmjs.com/package/erela.js-spotify) but its need lavalink server

**Comment by PavelHouze** [comment]
> > Sorry, I mean that i get song name from Spotify api and then try to search it in YouTube.searchsong. I tried a lot of ways to search it in YouTube.searchsong and it doesn't work.
> > My last hope was that you can help me or you have an example with Spotify integration.
> > Anyway, thank you for such a good bot.
> 
> Simple, not all songs on spotify available on youtube. You can use [this](https://www.npmjs.com/package/erela.js-spotify) but its need lavalink server

Thank you

**Comment by mozartrafi** [comment]
If you have further questions, you can [join our Discord server](https://zhycorp.xyz/discord).

**Comment by mozartrafi** [comment]
If you have further questions, you can do that by joining our [Discord server](https://zhycorp.xyz/discord)
