### ISSUE TITLE
Help command

### ISSUE THREAD

**Issue by Lowkik-Sai** [zhycorp/music-bot-example#50]
Hello Brother,
I need small help in pagination help command in your code,means i made a bot with music feature,mod and some other features!!!
Like you prepared for queue!
Please Help me to make my command
For each page, each command and description!
I don't know how to code like this and i tried pagination but package is not same,so it is not working for this music bot!

**Comment by mozartrafi** [comment]
If you need any support, you can join to [our Discord server](https://zhycorp.xyz/discord) instead of opening an issues
